markdown: redcarpet
comments: true
highligher: pygments
safe: true
permalink: /posts/:title
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

name: Skylight Symmetry
author: Si Beaumont
feedburner: skylightsymmetry
twitter: simonjbeaumont
instagram: simonjbeaumont
github: simonjbeaumont
disqus: skylightsymmetry

catcolors:
  software: 3a6476
  music: 973d59
  church: 69833f
